# Generated by Django 5.1.1 on 2024-10-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldCostLibrary', '0002_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_id',
            field=models.EmailField(default='rajpootabhishek63071@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
